twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    # form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        phone: '+ 33 12 14 15 16'

when@test:
    twig:
        strict_variables: true
